version: "3.8"

services:
  postgres:
    image: postgis/postgis:13-master
    environment:
      - POSTGRES_DB=recipe
      - POSTGRES_USER=recipe
      - POSTGRES_PASSWORD=recipe
    volumes:
      - ../recipe-volume/postgres:/var/lib/postgresql/data/
    ports:
      - "6432:5432"
  app:
    build: 
      context: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
  